### ISSUE TITLE
run error docker

### ISSUE THREAD

**Issue by coolcat97** [Jellayy/Invitarr#14]
2022-08-17 06:26:24,243 [root:INFO] INIT: Config file found

2022-08-17 06:26:24,255 [root:INFO] PLEXAPI: Logging into Account: ***********

2022-08-17 06:26:24,750 [root:INFO] PLEXAPI: Logged in!

2022-08-17 06:26:24,750 [root:INFO] PLEXAPI: Connecting to server: ***************

2022-08-17 06:26:25,083 [root:INFO] PLEXAPI: Connected!

2022-08-17 06:26:25,083 [root:INFO] SQLITE3: Connecting to DB

2022-08-17 06:26:25,083 [root:INFO] SQLITE3: Connected!

2022-08-17 06:26:25,084 [root:INFO] SQLITE3: Existing users table found

2022-08-17 06:26:25,084 [root:INFO] INIT: Role Monitoring enabled in config

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 618, in _load_from_module_spec

    setup(self)

  File "/app/utils/cogs/RoleMonitoring.py", line 70, in setup

    if client.parser.get('Overseer Account Management', 'Enable') == '1':

  File "/usr/local/lib/python3.10/configparser.py", line 782, in get

    d = self._unify_values(section, vars)

  File "/usr/local/lib/python3.10/configparser.py", line 1153, in _unify_values

    raise NoSectionError(section) from None

configparser.NoSectionError: No section: 'Overseer Account Management'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/app/bot.py", line 60, in <module>

    client.load_extension('utils.cogs.RoleMonitoring')

  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 678, in load_extension

    self._load_from_module_spec(spec, name)

  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 623, in _load_from_module_spec

    raise errors.ExtensionFailed(key, e) from e

discord.ext.commands.errors.ExtensionFailed: Extension 'utils.cogs.RoleMonitoring' raised an error: NoSectionError: No section: 'Overseer Account Management'

**Comment by coolcat97** [comment]
Won't start after spitting out this error.

**Comment by coolcat97** [comment]
same error with overseer section marked "0"

**Comment by Jellayy** [comment]
You're right in thinking that error relates to a missing key in the `/config/config.ini`. In the future I can make such errors more explicit for easier debug on the user side, especially if new versions require more fields in the config file, as v2 does.

Your error in particular is because Invitarr cannot find this block in your config:
```
[Overseer Account Management]
enable = 0
```
The way Invitarr parses the config file means that the formatting is pretty strict, so both section headers and value need to be there. If you don't feel like manually making sure this formatting is correct, you can delete your `config.ini` file and Invitarr will place a properly formatted v2 config file in its place that you can fill in on next run.
<br>
If everything is formatted correctly in your config file, the only other explanation I can think of is that Invitarr can't see it, which would mean something is wrong with the Docker bind mount or the files inside of that mount. 

Make sure that your container has a local bind mount to `/config` in the container and that your latest `config.ini` file is in there. You can double check this by starting a bash session in your container either through a GUI such as portainer or by running `docker exec -t -i container_name /bin/bash` and running `cat /config/config.ini` from within your container. (note: This might be a little hard to do as you can only do it while the container is running. Though there might be plenty of time if your plex account API times out as much as mine does :) )

**Comment by coolcat97** [comment]
Changed permissions to 0775, this seemed to fix! Thanks for the fast response!!!! <3
